//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee3Tier.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEmp", ReplyAction="http://tempuri.org/IService1/CreateEmpResponse")]
        int CreateEmp(EmployeeEntity.Entity emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateEmp", ReplyAction="http://tempuri.org/IService1/CreateEmpResponse")]
        System.Threading.Tasks.Task<int> CreateEmpAsync(EmployeeEntity.Entity emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployee", ReplyAction="http://tempuri.org/IService1/getEmployeeResponse")]
        EmployeeEntity.Entity[] getEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployee", ReplyAction="http://tempuri.org/IService1/getEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeEntity.Entity[]> getEmployeeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Employee3Tier.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Employee3Tier.ServiceReference2.IService1>, Employee3Tier.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateEmp(EmployeeEntity.Entity emp) {
            return base.Channel.CreateEmp(emp);
        }
        
        public System.Threading.Tasks.Task<int> CreateEmpAsync(EmployeeEntity.Entity emp) {
            return base.Channel.CreateEmpAsync(emp);
        }
        
        public EmployeeEntity.Entity[] getEmployee() {
            return base.Channel.getEmployee();
        }
        
        public System.Threading.Tasks.Task<EmployeeEntity.Entity[]> getEmployeeAsync() {
            return base.Channel.getEmployeeAsync();
        }
    }
}
